# Generated by Django 5.1.7 on 2025-04-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='notes',
        ),
    ]
