# Generated by Django 5.1.7 on 2025-04-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='trip.trip'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='trip.trip'),
        ),
    ]
