# Generated by Django 4.2.23 on 2025-07-23 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_dislikes_trip_likes_trip_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell others about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment_notifications',
            field=models.BooleanField(default=True, help_text='Notify when someone comments on your content'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can see'), ('registered', 'Registered Users Only'), ('private', 'Private - Only Me')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='featured_trips',
            field=models.ManyToManyField(blank=True, help_text='Select up to 3 trips to feature on your portfolio', related_name='featured_by_users', to='trip.trip'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Your current location', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photos_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can see'), ('registered', 'Registered Users Only'), ('private', 'Private - Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can see'), ('registered', 'Registered Users Only'), ('private', 'Private - Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reaction_notifications',
            field=models.BooleanField(default=True, help_text='Notify when someone reacts to your content'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_join_date',
            field=models.BooleanField(default=True, help_text='Show join date on profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_last_active',
            field=models.BooleanField(default=False, help_text='Show last active date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_trip_count',
            field=models.BooleanField(default=True, help_text='Show trip count on profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_facebook',
            field=models.CharField(blank=True, help_text='Facebook profile URL', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_instagram',
            field=models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_twitter',
            field=models.CharField(blank=True, help_text='Twitter username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System Default)')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trips_visibility',
            field=models.CharField(choices=[('public', 'Public - Anyone can see'), ('registered', 'Registered Users Only'), ('private', 'Private - Only Me')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal website or blog'),
        ),
    ]
